# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting 
# with 1 and 2, the first 10 terms will be:
# 		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find t
# he sum of the even-valued terms.

x = 1
y = 1
z = 0
total = 0
evenTotal = 0

fibVar = 4000000

while total < fibVar:
	z = x + y
	total = z
	if total > fibVar:
		break
	elif total % 2 == 0:
		evenTotal = evenTotal + total
	
	x = y + z
	total = x
	if total > fibVar:
		break
	elif total % 2 == 0:
		evenTotal = evenTotal + total
	
	y = x + z
	total = y
	if total % 2 == 0:
		evenTotal = evenTotal + total


print evenTotal

#Answer is 4613732 resulting in 33 iterations through the loop
	